name: Test package
on: [push, pull_request]
run-name: >
  Testing Package From ${{ github.event_name == 'pull_request' &&
      format('🔀 PR #{0} [{1}] - {2}',
        github.event.pull_request.number,
        github.head_ref,
        github.event.pull_request.title
      )
    ||
      format('➡️ Push [{0}]',
        github.ref_name
      )
  }}

jobs:
  testAllModes:
    permissions:
      checks: write
    environment: game.ci
    name: Test in ${{ matrix.testMode }} - ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        projectPath: [test-project/Packages/com.abrds.jam-starter]
        unityVersion: ['6000.4.1f1'] # some version must be included for package testing
        testMode: [editmode, playmode, Standalone]

    steps:
      - uses: actions/checkout@v4
        name: Download package
        with:
          lfs: true

      - name: Create test-project Directory & Copy package
        run: |
          PROJECT=${{ matrix.projectPath }}
          mkdir -p $PROJECT
          rsync -a --exclude test-project ./ $PROJECT      

      - name: Create TempProject Directory & Copy samples
        run: |
          SAMPLES=TempProject/Assets/Samples
          mkdir -p $SAMPLES
          rsync -a Samples~/ $SAMPLES      

      - uses: game-ci/unity-test-runner@v4
        name: Run Tests
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          packageMode: true
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+Jam-starter.*,+FixedPaletteTool.Runtime'
          customParameters: -nographics -batchmode

      - uses: actions/upload-artifact@v4
        name: Upload Artifacts
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}

      - uses: actions/upload-artifact@v4
        name: Upload Coverage Artifacts
        if: always()
        with:
          name: Coverage results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.coveragePath }}

      - name: Extract Unity Coverage & Add to Summary
        run: |
          FILE=${{ steps.tests.outputs.coveragePath }}/TempProject-opencov/Automated/TestCoverageResults_0000.xml

          if [ ! -f "$FILE" ]; then
            echo "Coverage file not found!" >> $GITHUB_STEP_SUMMARY
            exit 0
          fi

          LINE_RATE=$(grep -oP 'line-rate="\K[0-9.]+' "$FILE")
          BRANCH_RATE=$(grep -oP 'branch-rate="\K[0-9.]+' "$FILE")

          LINE_PERCENT=$(awk "BEGIN {printf \"%.2f\", $LINE_RATE * 100}")
          BRANCH_PERCENT=$(awk "BEGIN {printf \"%.2f\", $BRANCH_RATE * 100}")

          echo "## 🧪 Unity Code Coverage" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Line Coverage | ${LINE_PERCENT}% |" >> $GITHUB_STEP_SUMMARY
          echo "| Branch Coverage | ${BRANCH_PERCENT}% |" >> $GITHUB_STEP_SUMMARY