# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
        with:
            lfs: true
      - name: LFS Pull
        run: git lfs pull

      - name: LFS Debug
        run: git lfs ls-files

      - name: List Files and Sizes - Image Debug
        run: |
          cd Documentation~/Images
          echo "Listing all files and their sizes:"
          find . -type f -exec du -h {} + | sort -rh

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: WebsiteDocs~/package-lock.json
          node-version: 20
          cache: 'npm'
      - name: Set base URL for VitePress build
        run: |
          REPO_NAME=$(basename $(git rev-parse --show-toplevel))
          echo "VITE_BASE_URL=/${REPO_NAME}/" >> $GITHUB_ENV
      - name: Install dependencies & build
        run: | 
          cd WebsiteDocs~
          npm ci
          npm run docs:build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './WebsiteDocs~/.vitepress/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
